### ISSUE TITLE
useLazyLogin() - the error object does not get reset after a subsequent successful login

### ISSUE THREAD

**Issue by drupov** [niallmurphy-ie/drupal-react-oauth-provider#2]
`useLazyLogin()` would return an `error`-object if the login was not successful for any reason, e.g.

`Object { error: "invalid_grant", error_description: "The user credentials were incorrect.", message: "The user credentials were incorrect." }`

The problem is that on a subsequent successful login the `error`-object is still returned with the same values as above, instead of being invalidated (NULL-ified)

**Comment by niallmurphy-ie** [comment]
Hey, I will fix that in the coming days. Thanks for pointing it out.

**Comment by niallmurphy-ie** [comment]
@drupov If you update to 1.0.5, this is now fixed. The error gets nulled when the hook is run.

**Comment by drupov** [comment]
@niallmurphy-ie yes, works now! Thanks!
